server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:../certs/output/server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: server
    trust-store: file:../certs/output/server-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: need

logging:
  level:
    org.springframework.boot.web.embedded.tomcat: INFO
